const books = [
  {
    id: 1,
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    type: "technology",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    publisher: "Addison-Wesley Professional",
    publish_year: "October 21, 1994",
    page_counts: 416,
  },
  {
    id: 2,
    title: "Clean Coder Conduct Professional Programmers",
    type: "technology",
    author: "Robert Cecil Martin",
    publisher: "Pearson: 1st edition",
    publish_year: "May 13, 2011",
    page_counts: 256,
  },
  {
    id: 3,
    title: "Introduction to Algorithms",
    type: "technology",
    author:
      "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    publisher: "The MIT Press",
    publish_year: "September 1, 2009",
    page_counts: 1292,
  },
  {
    id: 4,
    title: "The Pragmatic Programmer",
    type: "technology",
    author: "Andrew Hunt, David Thomas",
    publisher: "Addison-Wesley Professional",
    publish_year: "September 13, 2019",
    page_counts: 352,
  },
  {
    id: 5,
    title: "Refactoring: Improving the Design of Existing Code",
    type: "technology",
    author: "Martin Fowler",
    publisher: "Addison-Wesley Professional",
    publish_year: "November 30, 2018",
    page_counts: 448,
  },
  {
    id: 6,
    title: "The Soul of a New Machine",
    type: "technology",
    author: "Tracy Kidder",
    publisher: "Back Bay Books",
    publish_year: "June 1, 2000",
    page_counts: 320,
  },
  {
    id: 7,
    title: "In the Plex: How Google Thinks, Works, and Shapes Our Lives",
    type: "technology",
    author: "Steven Levy",
    publisher: "Simon & Schuster",
    publish_year: "February 2, 2021",
    page_counts: 464,
  },
  {
    id: 8,
    title: "The Code: Silicon Valley and the Remaking of America",
    type: "technology",
    author: "Margaret O'Mara",
    publisher: "Penguin Books",
    publish_year: "July 7, 2020",
    page_counts: 512,
  },
  {
    id: 9,
    title:
      "Master Your Code: The Art, Wisdom, and Science of Leading an Extraordinary Life",
    type: "technology",
    author: "Darren J. Gold",
    publisher: "Kindle",
    publish_year: "September 24, 2019",
    page_counts: 220,
  },
  {
    id: 10,
    title: "AI Superpowers: China, Silicon Valley, and the New World Order",
    type: "technology",
    author: "Kai-Fu Lee",
    publisher: "Harper Business",
    publish_year: "September 25, 2018",
    page_counts: 272,
  },
];

module.exports = books;
