const users = [
  {
    id: 1,
    name: "Bima Antasena",
    email: "bima@gmail.com",
    password: "bima1234",
    gender: "male",
    roles: "admin",
    address:
      "Jl. Ahmad Dahlan No. 12E, Kabupaten Sleman, Daerah Istimewa Yogyakarta",
  },
  {
    id: 2,
    name: "Al Fajri Yunus",
    email: "fajri@gmail.com",
    password: "fajri1234",
    gender: "male",
    roles: "user",
    address: "Jl. Simpang Waringin No. 13A, Moyoketen, Kabupaten Tulungagung",
  },
  {
    id: 3,
    name: "Rendra Atmajaya",
    email: "rendra@gmail.com",
    password: "rendra1234",
    gender: "male",
    roles: "user",
    address: "Jl. Bunga Coklat No. 16, Kota Malang",
  },
  {
    id: 4,
    name: "Alfi Putri Sena",
    email: "alfi@gmail.com",
    password: "alfi1234",
    gender: "female",
    roles: "user",
    address: "Jl. Raya Demuk No. 21, Panjerejo, Rejoagung, Kota Padang",
  },
  {
    id: 5,
    name: "Sindy Amalia",
    email: "sindy@gmail.com",
    password: "sindy1234",
    gender: "female",
    roles: "user",
    address: "Jl. Tarumanegara No. 12B, Kota Medan",
  },
  {
    id: 6,
    name: "Ashole Ginting",
    email: "ashole@gmail.com",
    password: "ashole1234",
    gender: "male",
    roles: "user",
    address: "Jl. Raya Karawang, Batu, Malang",
  },
  {
    id: 7,
    name: "Fara Rizky Talinua",
    email: "fara@gmail.com",
    password: "fara1234",
    gender: "female",
    roles: "user",
    address: "Jl. Raya Gedangan, Kabupaten Tulungagung",
  },
  {
    id: 8,
    name: "Aryo Sudrajat",
    email: "aryo@gmail.com",
    password: "aryo1234",
    gender: "male",
    roles: "user",
    address: "Jl. Raya Idjen, Kota Malang",
  },
  {
    id: 9,
    name: "Hana Mahfud Sitompul",
    email: "hana@gmail.com",
    password: "hana1234",
    gender: "female",
    roles: "user",
    address: "Jl. Raya Popoh Indah, Kabupaten Tulungagung",
  },
  {
    id: 10,
    name: "Fikri Rahmat Darmawan",
    email: "fikri@gmail.com",
    password: "fikri1234",
    gender: "male",
    roles: "user",
    address: "Jl. Banteng Geringin No. 24B, Tasikmalaya",
  },
];

module.exports = users;
